import json
FILE_CHAT   = 'data_chat.json' #Bisa Di edit sesuaikan data yang udah di scrap dari discord
FILE_ITEMS  = 'Items.txt' #growtopia source
FILE_OUTPUT = 'laporan_supply_demand.txt' # Ini hasil output yang akan keluar
KEYWORDS_BUY  = ["buy", "buying", "wtb", "need", "b>", "looking for"]
KEYWORDS_SELL = ["sell", "selling", "wts", "s>", "have", "cheap"]

print("--- SYSTEM START: MARKET ANALYZER ---")
database_items = []
try:
    with open(FILE_ITEMS, 'r', encoding='utf-8') as f:
        next(f)
        for line in f:
            parts = line.strip().split('|') 
            if len(parts) >= 2:
                nama_item = parts[1].strip().lower()
                if len(nama_item) > 2: 
                    database_items.append(nama_item)
    print(f"[OK] Database dimuat: {len(database_items)} item terdaftar.")
except FileNotFoundError:
    print(f"[ERROR] File '{FILE_ITEMS}' tidak ditemukan!")
    exit()

try:
    with open(FILE_CHAT, 'r', encoding='utf-8') as f:
        data_json = json.load(f)
    print(f"[OK] Data Chat dimuat.")
except FileNotFoundError:
    print(f"[ERROR] File '{FILE_CHAT}' tidak ditemukan!")
    exit()
market_data = {}

print("Sedang menganalisa Supply & Demand... (Tunggu sebentar)")

messages = data_json.get('messages', [])
for msg in messages:
    content = msg.get('content', '').lower()
    if not content: continue
    item_ditemukan = None
    for item_name in database_items:
        if f" {item_name} " in f" {content} " or content == item_name:
            item_ditemukan = item_name
            break 
    if item_ditemukan:
        item_key = item_ditemukan.title()
        if item_key not in market_data:
            market_data[item_key] = {"buy": [], "sell": []}

        author = msg.get('author', {}).get('name', 'Unknown')
        waktu = msg.get('timestamp', '')[:19].replace('T', ' ')
        pesan_bersih = msg.get('content', '').replace('\n', ' ')
        log_entry = f"[{waktu}] {author}: {pesan_bersih}"

        is_buying = any(k in content for k in KEYWORDS_BUY)
        if is_buying:
            market_data[item_key]["buy"].append(log_entry)

        is_selling = any(k in content for k in KEYWORDS_SELL)
        if is_selling:
            market_data[item_key]["sell"].append(log_entry)

with open(FILE_OUTPUT, 'w', encoding='utf-8') as f_out:
    f_out.write(f"===== ANALISA MARKET SUPPLY & DEMAND =====\n")
    f_out.write(f"Generated by github : rikzyfy \n")
    f_out.write("="*60 + "\n\n")
    sorted_items = sorted(
        market_data.items(), 
        key=lambda x: len(x[1]['buy']) + len(x[1]['sell']), 
        reverse=True
    )

    for nama_item, data in sorted_items:
        count_buy = len(data['buy'])
        count_sell = len(data['sell'])
        total = count_buy + count_sell
        
        if total == 0: continue

        f_out.write(f"ITEM: {nama_item}\n")
        f_out.write(f"STATISTIK: Demand (Buy): {count_buy} | Supply (Sell): {count_sell}\n")
        
        if count_buy > count_sell * 2:
            status = ">> HIGH DEMAND (Barang Dicari!) <<"
        elif count_sell > count_buy * 2:
            status = ">> OVERSUPPLY (Barang Banjir!) <<"
        else:
            status = ">> STABIL <<"
        f_out.write(f"STATUS: {status}\n")
        f_out.write("-" * 60 + "\n")

        if count_buy > 0:
            f_out.write(f"  [Daftar Pembeli / Buyer]\n")
            for msg in data['buy']:
                f_out.write(f"   -> {msg}\n")
            f_out.write("\n")

        if count_sell > 0:
            f_out.write(f"  [Daftar Penjual / Seller]\n")
            for msg in data['sell']:
                f_out.write(f"   -> {msg}\n")
            f_out.write("\n")
        
        f_out.write("="*60 + "\n\n")

print(f"SELESAI! Cek file '{FILE_OUTPUT}' untuk melihat Supply & Demand.")
